name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Setup .NET ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # --- Restore solution ---
      - name: Restore solution
        run: dotnet restore Projekt_razvoj.sln

      # --- Restore test project ---
      - name: Restore test project
        run: dotnet restore Projekt_razvoj.Tests/Projekt_razvoj.Tests.csproj

      # --- Run Tests ---
      - name: Run tests
        run: dotnet test Projekt_razvoj.Tests --no-build --logger:trx

      # --- Debug: show where trx files are ---
      - name: Debug TRX files
        if: always()
        run: |
          echo "Searching for trx files..."
          find . -name "*.trx" -print

      # --- Save test results ---
      - name: Save test results as artifact
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Test results"
          path: "**/*.trx"
          reporter: dotnet-trx

      # --- Docker Build ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            lejicjesiptar69/projekt_kultura:latest
            lejicjesiptar69/projekt_kultura:${{ github.sha }}
